/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IPikachuInterface extends utils.Interface {
  functions: {
    "borrow(address,address,uint256,uint256,uint256,bytes,uint256,uint256)": FunctionFragment;
    "repay(address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "borrow" | "repay"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "borrow",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;

  events: {
    "CreatedLoan(address,address,uint256)": EventFragment;
    "CreatedPool(address,uint256,uint256)": EventFragment;
    "LiquidatedLoan(address,address,uint256)": EventFragment;
    "UpdatedPool(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatedLoan"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatedPool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidatedLoan"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedPool"): EventFragment;
}

export interface CreatedLoanEventObject {
  poolOwner: string;
  borrower: string;
  amount: BigNumber;
}
export type CreatedLoanEvent = TypedEvent<
  [string, string, BigNumber],
  CreatedLoanEventObject
>;

export type CreatedLoanEventFilter = TypedEventFilter<CreatedLoanEvent>;

export interface CreatedPoolEventObject {
  poolOwner: string;
  poolId: BigNumber;
  amount: BigNumber;
}
export type CreatedPoolEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  CreatedPoolEventObject
>;

export type CreatedPoolEventFilter = TypedEventFilter<CreatedPoolEvent>;

export interface LiquidatedLoanEventObject {
  poolOwner: string;
  borrower: string;
  amount: BigNumber;
}
export type LiquidatedLoanEvent = TypedEvent<
  [string, string, BigNumber],
  LiquidatedLoanEventObject
>;

export type LiquidatedLoanEventFilter = TypedEventFilter<LiquidatedLoanEvent>;

export interface UpdatedPoolEventObject {
  poolOwner: string;
  poolId: BigNumber;
}
export type UpdatedPoolEvent = TypedEvent<
  [string, BigNumber],
  UpdatedPoolEventObject
>;

export type UpdatedPoolEventFilter = TypedEventFilter<UpdatedPoolEvent>;

export interface IPikachu extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPikachuInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    borrow(
      _poolOwner: PromiseOrValue<string>,
      _collection: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      _floorPrice: PromiseOrValue<BigNumberish>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    repay(
      _poolOwner: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  borrow(
    _poolOwner: PromiseOrValue<string>,
    _collection: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _duration: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    _signature: PromiseOrValue<BytesLike>,
    _floorPrice: PromiseOrValue<BigNumberish>,
    _blockNumber: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  repay(
    _poolOwner: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    borrow(
      _poolOwner: PromiseOrValue<string>,
      _collection: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      _floorPrice: PromiseOrValue<BigNumberish>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    repay(
      _poolOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CreatedLoan(address,address,uint256)"(
      poolOwner?: PromiseOrValue<string> | null,
      borrower?: PromiseOrValue<string> | null,
      amount?: null
    ): CreatedLoanEventFilter;
    CreatedLoan(
      poolOwner?: PromiseOrValue<string> | null,
      borrower?: PromiseOrValue<string> | null,
      amount?: null
    ): CreatedLoanEventFilter;

    "CreatedPool(address,uint256,uint256)"(
      poolOwner?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): CreatedPoolEventFilter;
    CreatedPool(
      poolOwner?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): CreatedPoolEventFilter;

    "LiquidatedLoan(address,address,uint256)"(
      poolOwner?: PromiseOrValue<string> | null,
      borrower?: PromiseOrValue<string> | null,
      amount?: null
    ): LiquidatedLoanEventFilter;
    LiquidatedLoan(
      poolOwner?: PromiseOrValue<string> | null,
      borrower?: PromiseOrValue<string> | null,
      amount?: null
    ): LiquidatedLoanEventFilter;

    "UpdatedPool(address,uint256)"(
      poolOwner?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null
    ): UpdatedPoolEventFilter;
    UpdatedPool(
      poolOwner?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null
    ): UpdatedPoolEventFilter;
  };

  estimateGas: {
    borrow(
      _poolOwner: PromiseOrValue<string>,
      _collection: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      _floorPrice: PromiseOrValue<BigNumberish>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    repay(
      _poolOwner: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    borrow(
      _poolOwner: PromiseOrValue<string>,
      _collection: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      _floorPrice: PromiseOrValue<BigNumberish>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    repay(
      _poolOwner: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
